### ISSUE TITLE
Cathook continues crashing every 5 - 10 minutes, sometimes less.

### ISSUE THREAD

**Issue by haxnoob** [nullworks/cathook#1812]
## System Information
**OS: Debian GNU/Linux 11 (bullseye) x86_64 **  
**DE: *Xfce 4.16*  
**Cathook Version: Latest Version (Master Branch)**  

## Description  
Cathook crashes TF2 very easily and sometimes randomly. It could even make TF2 crash if you try killing an Enemy class/player sometimes.
It pretty much just crashes on Casual servers, so it could be either VAC trying to ban or Cathook or the Game having an issue.
Also, Cathook seems to be only running for 5 - 10 minutes. It only ran one time for 30 minutes.
I'm surprised this cheat is being updated still but the developers won't bother fixing bugs and stuff that cause Cathook and TF2 to crash and/or finding a way to stop VAC from trying to ban you very fast. Is anyone even going to fix this cheat or what?
## Steps to reproduce  
- [Y] I am able to consistently reproduce this error

1. Launch TF2.
2. Inject Cathook and enter a Casual server.
3. Do literally anything and Cathook will crash in 5 - 10 minutes or maybe less.

## Checklist  
- [Y] I have included my DE, WM, and version of Cathook.
- [Y] I have included the steps to reproduce and my logs to the best I am able to share.
- [Y] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here) (I currently do not have Telegram)

**Comment by snipergaming134** [comment]
> ## System Information
> **OS: Debian GNU/Linux 11 (bullseye) x86_64 ** **DE: _Xfce 4.16_ **Cathook Version: Latest Version (Master Branch)**
> 
> ## Description
> Cathook crashes TF2 very easily and sometimes randomly. It could even make TF2 crash if you try killing an Enemy class/player sometimes. It pretty much just crashes on Casual servers, so it could be either VAC trying to ban or Cathook or the Game having an issue. Also, Cathook seems to be only running for 5 - 10 minutes. It only ran one time for 30 minutes. I'm surprised this cheat is being updated still but the developers won't bother fixing bugs and stuff that cause Cathook and TF2 to crash and/or finding a way to stop VAC from trying to ban you very fast. Is anyone even going to fix this cheat or what?
> 
> ## Steps to reproduce
> * [Y] I am able to consistently reproduce this error
> 
> Steps to reproduce the behavior:
> 
> 1. Launch TF2.
> 2. Inject Cathook and enter a Casual server.
> 3. Do literally anything and Cathook will crash in 5 - 10 minutes or maybe less.
> 
> ## Checklist
> * [Y] I have included my DE, WM, and version of Cathook.
> * [Y] I have included the steps to reproduce and my logs to the best I am able to share.
> * [Y] The Developers are allowed to contact me on [the official telegram](https://t.me/nullworks) for further information if they need it. (Put your username here) (I currently do not have Telegram)

imagine using cathook as a cheating source rather than a botting source which is what it was made for

**Comment by oukhali99** [comment]
I just reproduced this issue with using the developer build and attach-gdb. When the game crashes, this is outputted

```
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
tcmalloc::SLL_Pop (list=<optimized out>) at src/linked_list.h:59
59      src/linked_list.h: No such file or directory.
#0  tcmalloc::SLL_Pop (list=<optimized out>) at src/linked_list.h:59
#1  tcmalloc::ThreadCache::FreeList::Pop (this=0x945f978) at src/thread_cache.h:216
#2  tcmalloc::ThreadCache::Allocate (cl=<optimized out>, size=144, this=<optimized out>) at src/thread_cache.h:368
#3  (anonymous namespace)::do_malloc_small (size=144, heap=<optimized out>) at src/tcmalloc.cc:1103
#4  (anonymous namespace)::do_malloc_no_errno (size=132) at src/tcmalloc.cc:1110
#5  (anonymous namespace)::do_malloc (size=132) at src/tcmalloc.cc:1119
#6  (anonymous namespace)::do_malloc_or_cpp_alloc (size=132) at src/tcmalloc.cc:1039
#7  tc_malloc (size=132) at src/tcmalloc.cc:1578
#8  0xf6184142 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/libtier0.so
#9  0xd5ac9758 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#10 0xd5ac9798 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#11 0xd5ac8402 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#12 0xd5ac89d6 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#13 0xd5b29dfc in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#14 0xd5b2c73f in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#15 0xd5b3200f in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#16 0xd5aecb11 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#17 0xd5b21d2a in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#18 0xd5b4709f in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#19 0xd5b46611 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#20 0xd5b46cc2 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#21 0xd5850f7a in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#22 0xd5851dfe in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#23 0xd58522e3 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#24 0xf152fdb5 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#25 0xf1530047 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#26 0xf143a1a0 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#27 0xd5dd85b8 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#28 0xd5de5c12 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#29 0xd5b16f87 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#30 0xd5b172f7 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#31 0xd5af0913 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#32 0xd5af1463 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#33 0xd5af1d70 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/tf/bin/client.so
#34 0xcd3b212f in ?? () from /tmp/.glAvYkkf
#35 0xf138ec62 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#36 0xf14633c9 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#37 0xf1474239 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#38 0xf1479e75 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#39 0xf148e5c7 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#40 0xf148e926 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#41 0xf148e96d in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#42 0xf1566ccb in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#43 0xf1562d90 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#44 0xf1562ebd in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#45 0xf15cbad8 in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#46 0xf1564c0f in ?? () from /media/oussamak/extra-storage/SteamLibrary/steamapps/common/Team Fortress 2/bin/engine.so
#47 0xf61d3118 in ?? ()
#48 0xf61d3118 in ?? ()
#49 0xf61b2ae6 in ?? ()
#50 0x080487ed in main ()
[Inferior 1 (process 52929) detached]
```

Also, here are the logs. The crash occurred at [17:48:57] and the error is a linked list error. So maybe the linked list for addPlayer is breaking somehow?

[debug
[cathook-oussamak-52929-segfault.log](https://github.com/nullworks/cathook/files/11492361/cathook-oussamak-52929-segfault.log)
[cathook-oussamak-52929.log](https://github.com/nullworks/cathook/files/11492362/cathook-oussamak-52929.log)
.conf.txt](https://github.com/nullworks/cathook/files/11492355/debug.conf.txt)

**Comment by oukhali99** [comment]
Adding more logs
[cathook-oussamak-125866.log](https://github.com/nullworks/cathook/files/11493454/cathook-oussamak-125866.log)
[cathook-oussamak-125866-segfault.log](https://github.com/nullworks/cathook/files/11493455/cathook-oussamak-125866-segfault.log)
[debug.conf.txt](https://github.com/nullworks/cathook/files/11493458/debug.conf.txt)
