### ISSUE TITLE
Cant Inject cathook

### ISSUE THREAD

**Issue by jeteki** [nullworks/cathook#1814]
Running instances: 16365
Attaching to 16365
loading /tmp/.glpVA8oz to 16365
[New LWP 16366]
[New LWP 16369]
[New LWP 16371]
[New LWP 16372]
[New LWP 16375]
[New LWP 16393]
[New LWP 16395]
[New LWP 16397]
[New LWP 16398]
[New LWP 16399]
[New LWP 16400]
[New LWP 16414]
[New LWP 16415]
[New LWP 16416]
[New LWP 16417]
[New LWP 16418]
[New LWP 16419]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
warning: Expected absolute pathname for libpthread in the inferior, but got .gnu_debugdata for target:/app/lib/i386-linux-gnu/libc.so.6.
warning: Expected absolute pathname for libpthread in the inferior, but got target:/app/lib/i386-linux-gnu/libc.so.6.
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
0xf7fbd549 in __kernel_vsyscall ()
Calling dlopen
$1 = (void *) 0x0
Calling dlerror
$2 = 0x2f4bf730 "/tmp/.glpVA8oz: cannot open shared object file: No such file or directory"
[Inferior 1 (process 16365) detached]

**Comment by Pichulol** [comment]
Are you still having this issue?

**Comment by jeteki** [comment]
> Are you still having this issue?

Nope just switched to master branch and that worked!

**Comment by mkuehn94** [comment]
same problem:
max@klapprechner1 ~/D/g/cathook ((26593d6f))> sudo ./attach-gdb
Running instances: 66338
Attaching to 66338
loading /tmp/.gleSyw15 to 66338
[New LWP 66340]
[New LWP 66341]
[New LWP 66344]
[New LWP 66345]
[New LWP 66348]
[New LWP 66482]
[New LWP 66484]
[New LWP 66644]
[New LWP 66645]
[New LWP 66646]
[New LWP 66648]
[New LWP 66764]
[New LWP 66765]
[New LWP 66766]
[New LWP 66767]
[New LWP 66768]
[New LWP 66784]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7f07579 in __kernel_vsyscall ()
Calling dlopen
$1 = (void *) 0x318fd340
Calling dlerror
$2 = 0x0
^C
Thread 1 "hl2_linux" received signal SIGINT, Interrupt.
0xf7f07579 in __kernel_vsyscall ()
#0  0xf7f07579 in __kernel_vsyscall ()
#1  0xf7cd9bc9 in __clock_nanosleep_time64 () from /usr/lib32/libc.so.6
#2  0xf7cdfb39 in nanosleep () from /usr/lib32/libc.so.6
#3  0xef3c3b1b in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0
#4  0xef34040e in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0
#5  0xef33b1a6 in SDL_WaitEventTimeout () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libSDL2-2.0.so.0
#6  0xed8a347a in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#7  0xed89f490 in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#8  0xed89f5bd in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#9  0xed908248 in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#10 0xed8a130f in ?? () from /home/max/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#11 0xf7328118 in ?? ()
#12 0xf7328118 in ?? ()
#13 0xf7307ae6 in ?? ()
#14 0x080487ed in main ()
[Inferior 1 (process 66338) detached]
max@klapprechner1 ~/D/g/cathook ((26593d6f))> sudo ./attach
Running instances: 66338
Attaching to 66338
loading /tmp/.gl1ZNu61 to 66338
[New LWP 66340]
[New LWP 66341]
[New LWP 66344]
[New LWP 66345]
[New LWP 66348]
[New LWP 66482]
[New LWP 66484]
[New LWP 66644]
[New LWP 66645]
[New LWP 66646]
[New LWP 66648]
[New LWP 66764]
[New LWP 66765]
[New LWP 66766]
[New LWP 66767]
[New LWP 66768]
[New LWP 66784]
warning: Could not load shared library symbols for 2 libraries, e.g. bin/launcher.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7f07579 in __kernel_vsyscall ()
Calling dlopen
$1 = (void *) 0x318fec00
Calling dlerror
$2 = 0x0
[Inferior 1 (process 66338) detached]

**Comment by sumdudinhell** [comment]
hey, i fixed it! edit attach with a text editor and replace everything with
```
#!/usr/bin/env bash

# Verify that we are root
if [ ! $(id -u) -eq 0 ]; then
    echo -e "\033[1;33m \n \nThis script must be ran as root!\n\033[0m"
    exit 1
fi

[[ ! -z "$SUDO_USER" ]] && RUNUSER="$SUDO_USER" || RUNUSER="$LOGNAME"
RUNCMD="sudo -u $RUNUSER"

$RUNCMD bash ./scripts/updater true
$RUNCMD bash ./report-crash true

line=$(pgrep -u $RUNUSER hl2_linux)
arr=($line)

if [ $# == 1 ]; then
    proc=$1
else
    if [ ${#arr[@]} == 0 ]; then
        echo TF2 isn\'t running!
        exit 1
    fi
    proc=${arr[0]}
fi

echo Running instances: "${arr[@]}"
echo Attaching to "$proc"

#sudo ./detach $inst bin/libcathook.so

#if grep -q "$(realpath bin/libcathook.so)" /proc/"$proc"/maps; then
#  echo already loaded
#  exit
#fi

FILENAME="/tmp/.gl$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)"

cp "bin/libcathook.so" "$FILENAME"

echo loading "$FILENAME" to "$proc"

gdbbin="gdb"
$gdbbin -n -q -batch                                                        \
    -ex "attach $proc"                                                  \
    -ex "echo \033[1mCalling dlopen\033[0m\n"                           \
    -ex "call ((void*(*)(const char*, int))dlopen)(\"$FILENAME\", 1)"   \
    -ex "echo \033[1mCalling dlerror\033[0m\n"                          \
    -ex "call ((char*(*)(void))dlerror)()"                              \
    -ex "detach"                                                        \
    -ex "quit"

rm $FILENAME
```
now you can inject and stream snipe trans streamers!
