### ISSUE TITLE
whenever i try to open the gui in the newui branch

### ISSUE THREAD

**Issue by Clairnet** [nullworks/cathook#561]
[clairnet@clairnet-pc cathook]$ sudo ./attach-backtrace
Running instances: 31897
Attaching to 31897
Running instances: 31897
Detaching from 31897
not found!
loading /home/clairnet/cathook/bin/libcathook.so to 31897
[New LWP 31898]
[New LWP 31900]
[New LWP 31902]
[New LWP 31903]
[New LWP 31920]
[New LWP 31922]
[New LWP 31959]
[New LWP 31960]
[New LWP 31961]
[New LWP 31962]
[New LWP 31977]
[New LWP 31978]
[New LWP 31979]
[New LWP 31980]
[New LWP 31981]
[New LWP 31982]
[New LWP 31983]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7f43049 in __kernel_vsyscall ()
[New Thread 0xec8bbb40 (LWP 32061)]
$1 = (void *) 0x22766840
'dlerror' has unknown return type; cast the call to its declared return type
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])

Thread 1 "hl2_linux" received signal SIGABRT, Aborted.
0xf7f43049 in __kernel_vsyscall ()
#0  0xf7f43049 in __kernel_vsyscall ()
#1  0xf7ce9082 in raise () from /usr/lib32/libc.so.6
#2  0xf7cd32b6 in abort () from /usr/lib32/libc.so.6
#3  0xf7ecde8a in tcmalloc::Log (mode=tcmalloc::kCrash, filename=0xf7edf6b6 "src/tcmalloc.cc", line=278, a=..., b=..., c=..., d=...) at src/internal_logging.cc:120
#4  0xf7ec935d in (anonymous namespace)::InvalidFree (ptr=0x2a2725) at src/tcmalloc.cc:278
#5  0xf7eda762 in (anonymous namespace)::free_null_or_invalid (ptr=0x2a2725, invalid_free_fn=0xf7ec92b0 <(anonymous namespace)::InvalidFree(void*)>) at src/tcmalloc.cc:1141
#6  (anonymous namespace)::do_free_helper (heap_must_be_valid=true, heap=0x87948e4, ptr=0x2a2725, invalid_free_fn=<optimized out>) at src/tcmalloc.cc:1185
#7  (anonymous namespace)::do_free_with_callback (ptr=0x2a2725, invalid_free_fn=<optimized out>) at src/tcmalloc.cc:1225
#8  (anonymous namespace)::do_free (ptr=0x2a2725) at src/tcmalloc.cc:1234
#9  tc_free (ptr=0x2a2725) at src/tcmalloc.cc:1585
#10 0xf23df006 in inflateReset2 () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#11 0xf1bd2843 in inflateInit2_ () from /usr/lib32/libz.so.1
#12 0xecb33579 in ?? () from /usr/lib32/libpng16.so.16
#13 0xecb38ef4 in ?? () from /usr/lib32/libpng16.so.16
#14 0xecb29eba in png_read_update_info () from /usr/lib32/libpng16.so.16
#15 0xd3e1371c in png::info::update (this=0xffb18584) at /home/clairnet/cathook/external/libglez/pngpp/info.hpp:166
#16 0xd3e1861d in png::reader<std::basic_ifstream<char, std::char_traits<char> > >::update_info (this=0xffb18580) at /home/clairnet/cathook/external/libglez/pngpp/reader.hpp:143
#17 0xd3e17f29 in png::consumer<png::basic_rgba_pixel<unsigned char>, png::image<png::basic_rgba_pixel<unsigned char>, png::pixel_buffer<png::basic_rgba_pixel<unsigned char> > >::pixel_consumer, png::image_info_ref_holder, true>::read<std::basic_ifstream<char, std::char_traits<char> >, png::convert_color_space<png::basic_rgba_pixel<unsigned char> > > (this=0xffb18624, stream=..., transform=...) at /home/clairnet/cathook/external/libglez/pngpp/consumer.hpp:190
#18 0xd3e17557 in png::image<png::basic_rgba_pixel<unsigned char>, png::pixel_buffer<png::basic_rgba_pixel<unsigned char> > >::read_stream<std::basic_ifstream<char, std::char_traits<char> >, png::convert_color_space<png::basic_rgba_pixel<unsigned char> > > (this=0xffb1883c, stream=..., transform=...) at /home/clairnet/cathook/external/libglez/pngpp/image.hpp:252
#19 0xd3e168c9 in png::image<png::basic_rgba_pixel<unsigned char>, png::pixel_buffer<png::basic_rgba_pixel<unsigned char> > >::read<png::convert_color_space<png::basic_rgba_pixel<unsigned char> > > (this=0xffb1883c, filename=0x2c02d92c "/opt/cathook/data/menu/cross.png", transform=...) at /home/clairnet/cathook/external/libglez/pngpp/image.hpp:212
#20 0xd3e15913 in png::image<png::basic_rgba_pixel<unsigned char>, png::pixel_buffer<png::basic_rgba_pixel<unsigned char> > >::read<png::convert_color_space<png::basic_rgba_pixel<unsigned char> > > (this=0xffb1883c, filename=..., transform=...) at /home/clairnet/cathook/external/libglez/pngpp/image.hpp:187
#21 0xd3e14add in png::image<png::basic_rgba_pixel<unsigned char>, png::pixel_buffer<png::basic_rgba_pixel<unsigned char> > >::image (this=0xffb1883c, filename=...) at /home/clairnet/cathook/external/libglez/pngpp/image.hpp:119
#22 0xd3e12a1c in glez::detail::texture::texture::load (this=0x2cfa7000, path=...) at /home/clairnet/cathook/external/libglez/src/detail/texture.cpp:51
#23 0xd3e11fab in glez::texture::load (this=0xd5383814 <cross>) at /home/clairnet/cathook/external/libglez/src/texture.cpp:22
#24 0xd3e11892 in glez::draw::rect_textured (x=678, y=200, w=16, h=16, color=..., texture=..., tx=0, ty=0, tw=16, th=16, angle=0) at /home/clairnet/cathook/external/libglez/src/draw.cpp:256
#25 0xd3de9c09 in zerokernel::WindowCloseButton::render (this=0x1faf87e0) at /home/clairnet/cathook/src/visual/menu/menu/wm/WindowCloseButton.cpp:27
#26 0xd3dc06a7 in zerokernel::Container::render (this=0x13c1fe10) at /usr/include/c++/8.2.0/bits/unique_ptr.h:342
#27 0xd3deb861 in zerokernel::WindowHeader::render (this=0x13c1fe10) at /home/clairnet/cathook/src/visual/menu/menu/wm/WindowHeader.cpp:73
#28 0xd3dc06a7 in zerokernel::Container::render (this=0x2c2c8520) at /usr/include/c++/8.2.0/bits/unique_ptr.h:342
#29 0xd3de7264 in zerokernel::WMWindow::render (this=0x2c2c8520) at /home/clairnet/cathook/src/visual/menu/menu/wm/WMWindow.cpp:59
#30 0xd3dea498 in zerokernel::WindowContainer::render (this=0x13c20150) at /usr/include/c++/8.2.0/bits/unique_ptr.h:342
#31 0xd3dc06a7 in zerokernel::Container::render (this=0x13c20220) at /usr/include/c++/8.2.0/bits/unique_ptr.h:342
#32 0xd3daeb6e in zerokernel::Menu::render (this=0x2ca1e580) at /usr/include/c++/8.2.0/bits/unique_ptr.h:342
#33 0xd3dedf7b in gui::draw () at /home/clairnet/cathook/src/visual/menu/GuiInterface.cpp:147
#34 0xd3d9a4e4 in DrawCheatVisuals () at /home/clairnet/cathook/src/visual/drawmgr.cpp:183
#35 0xd3d9a838 in render_cheat_visuals () at /home/clairnet/cathook/src/visual/drawmgr.cpp:31
#36 0xd3d5d489 in hooked_methods::methods::Paint (this_=<optimized out>, mode=<optimized out>) at /home/clairnet/cathook/src/hooks/Paint.cpp:94
#37 0xf2280027 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#38 0xf22803fd in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#39 0xf215b71b in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#40 0xf216c4a9 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#41 0xf2172105 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#42 0xf21873c7 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#43 0xf2187726 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#44 0xf218776d in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#45 0xf225edbb in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#46 0xf225ae80 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#47 0xf225afad in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#48 0xf22c30c8 in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#49 0xf225ccff in ?? () from /home/clairnet/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#50 0xf63e3428 in ?? ()
#51 0xf63e3428 in ?? ()
#52 0xf63c3896 in ?? ()
#53 0x080487ed in main ()

**Comment by BenCat07** [comment]
png read machine broke, can't really fix that
